gatling.enterprise.package {
  # id = "00000000-0000-0000-0000-000000000000"
  name = "My package name"
  team = "My team name"
  simulations = [
    {
      # id = "00000000-0000-0000-0000-000000000001"
      name = "My simulation name"
      simulation = "com.example.SimulationA"
      locations = [
        {
          name: "Europe - Paris",
          size: 2,
          weight: 30
        },
        {
          name: "AP Pacific - Mumbai",
          size: 2,
          weight: 70
        }
      ]
      parameters {
        ignoreDefaults = false
        systemProperties {
          "com.example.prop.1" = "system prop 1"
          "com.example.prop.2" = "system prop 2"
        }
        environmentVariables {
          SIMULATION_ENV_VAR_1 = "environment 1"
          SIMULATION_ENV_VAR_2 = "environment 2"
        }
      }
      timeWindow {
        rampUp = 10
        rampDown = 10
      }
      stopCriteria = [
        {
          type = "meanCpu",
          timeframeInSeconds = 10,
          threshold = {
            maxPercentage = 90
          }
        },
        {
          type = "globalResponseTime",
          timeframeInSeconds = 10,
          threshold = {
            maxMilliseconds = 90,
            percentile = 50
          }
        },
        {
          type = "globalErrorRatio",
          timeframeInSeconds = 10,
          threshold = {
            maxPercentage = 90
          }
        }
      ]
    }
  ]
}
